
const trailers = [
{link: 'https://www.youtube.com/watch?v=IAdCsNtEuBU'},
{link: 'https://www.youtube.com/watch?v=044PUmZQd1g'},
{link: 'https://www.youtube.com/watch?v=beToTslH17s'},
{link: 'https://www.youtube.com/watch?v=eqCYw_o5lng'},
{link: 'https://www.youtube.com/watch?v=9Ji5U2sTlLU'},
{link: 'https://www.youtube.com/watch?v=IiMinixSXII'},
{link: 'https://www.youtube.com/watch?v=1o8GWhoD53I'},
{link: 'https://www.youtube.com/watch?v=5YEVQDr2f3Q'},
{link: 'https://www.youtube.com/watch?v=2NnPzpuU5ao'},
{link: 'https://www.youtube.com/watch?v=DuWEEKeJLMI'},
{link: 'https://www.youtube.com/watch?v=lav0rFNh3OI'},
{link: 'https://www.youtube.com/watch?v=_Z3QKkl1WyM'},
{link: 'https://www.youtube.com/watch?v=kNgi8ZZh2qY'},
{link: 'https://www.youtube.com/watch?v=X0tOpBuYasI'},
{link: 'https://www.youtube.com/watch?v=wUn05hdkhjM'},
{link: 'https://www.youtube.com/watch?v=ViKnrHjzgn4'},
{link: 'https://www.youtube.com/watch?v=70e5RjgkHjU'},
{link: 'https://www.youtube.com/watch?v=060mO4hRu3w'},
{link: 'https://www.youtube.com/watch?v=AiohkY_XQYQ'},
{link: 'https://www.youtube.com/watch?v=0wiBHEACNHs'},
{link: 'https://www.youtube.com/watch?v=SRDGQZHsiGg'},
{link: 'https://www.youtube.com/watch?v=kVlPF24TXsM'},
{link: 'https://www.youtube.com/watch?v=k98Afd7Nf3Y'},
{link: 'https://www.youtube.com/watch?v=A0wg3Zkxq1c'},
{link: 'https://www.youtube.com/watch?v=iSspRSGc4Dk'},
{link: 'https://www.youtube.com/watch?v=Go8nTmfrQd8'},
{link: 'https://www.youtube.com/watch?v=DQ0UqBQ_AII'},
{link: 'https://www.youtube.com/watch?v=JfVOs4VSpmA'},
{link: 'https://www.youtube.com/watch?v=nju7pbZ-VBs'},
{link: 'https://www.youtube.com/watch?v=giXco2jaZ_4'},
{link: 'https://www.youtube.com/watch?v=d96cjJhvlMA'},
{link: 'https://www.youtube.com/watch?v=OYhFFQl4fLs'},
{link: 'https://www.youtube.com/watch?v=kQTLklkqfZw'},
{link: 'https://www.youtube.com/watch?v=WR_ObUyyaL8&pp=ygUPcmlwZCAyICB0cmFpbGVy'},
{link: 'https://www.youtube.com/watch?v=aWzlQ2N6qqg'},
{link: 'https://www.youtube.com/watch?v=pyM3z73oMAk'},
{link: 'https://www.youtube.com/watch?v=wyiZWYMilgk'},
{link: 'https://www.youtube.com/watch?v=G5kzUpWAusI'},
{link: 'https://www.youtube.com/watch?v=T5HMoxJRhRY'},
{link: 'https://www.youtube.com/watch?v=QwievZ1Tx-8'},
{link: 'https://www.youtube.com/watch?v=mr46Twz-BII'},
{link: 'https://www.youtube.com/watch?v=oJYJmYQ0AGw'}
]

export default trailers